### ISSUE TITLE
Fullscreen GVIM & roxterm fails

### ISSUE THREAD

**Issue by ideasman42** [sulami/FrankenWM#27]
Making any window fullscreen (that uses incremental resizing), fails

it flickers, then restores to regular size.

**Comment by sulami** [comment]
So this seems to have to do with roxterm (which is what I tested) sending its own configurerequest upon resize to set its own dimensions. This can partially be circumvented by not tiling after receiving a configurerequest (that demands a resize), see line 704/frankenwm.c. Possible solutions could be honoring this request and resizing the window, but any call to `tile()` would break this, and `tile()` gets called quite often, as you might have noticed.

I am not quite sure yet if this is actually a bug or a wontfix because it is a bug in those programs that do not accept arbitrary window sizes like they should.
