### ISSUE TITLE
Per window border size/color for application specific rules

### ISSUE THREAD

**Issue by svanrossem** [sulami/FrankenWM#65]
It would be nice if we can set the border size of specific windows matched to their rules.
Like;
```
static const AppRule rules[] = { \
    /* title regex  desktop  follow  float  border_width  border_color */
    { "GNU Image",  -1,      False,  True,  3,            "#ffffff" },
    { "Skype",       3,      False,  True,  3,            "#ffffff" },
    { "Chromium",    2,      False,  True,  0,            "#ffffff" },
    { "xterm",      -1,      False,  False, 5,            "#ff00aa" },
};
```
The Awesome implementation; http://awesome.naquadah.org/wiki/Understanding_Rules#Getting_Started

**Comment by sulami** [comment]
On Wed, Feb 17, 2016 at 05:23:57AM -0800, Sander van Rossem wrote:
> It would be nice if we can set the border size of specific windows matched to their rules.
> Like;
> ```
> static const AppRule rules[] = { \
>     /* title regex  desktop  follow  float  border_width  border_color */
>     { "GNU Image",  -1,      False,  True,  3,            "#ffffff" },
>     { "Skype",       3,      False,  True,  3,            "#ffffff" },
>     { "Chromium",    2,      False,  True,  0,            "#ffffff" },
>     { "xterm",      -1,      False,  False, 5,            "#ff00aa" },
> };
> ```
> The Awesome implementation; http://awesome.naquadah.org/wiki/Understanding_Rules#Getting_Started
> 

Hm, this should be possible without interfering with the tiling
mechanism. I can probably write this some time this weekend.

-- 

Robin Schroer

**Comment by sulami** [comment]
So, custom border sizes via AppRules are now in master (and the newest AUR version as well). I tested this for a bit without any issues, but there might still be some issues with specific layouts not being properly aligned under some circumstances. If this happens, please report it so I can fix that. 

Values >= 0 are overriding the global border width, anything negative means just use the default one. I have thought about custom colors, but I'm not sure that would bring much extra use and possibly impact usability. Feel free to argue otherwise if you really want this feature.
